spring:
  datasource:
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 8000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 350
      minimum-idle: 10
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://218.104.49.220:3306/ctgdb?characterEncoding=utf-8&allowMultiQueries=true
    username: hfj
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
